# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Local PDF asset
resume_simplified: /assets/pdf/resume_simplified.pdf

# Content configuration version
version: 2

# Personal info
name: Andrew Mounsey
title: GIS Enterprise Manager
email: andrew3784@hotmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  andrew3784
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Resume
#   icon: fas fa-globe
#    url: https://github.com/andrew3784/andrew3784.github.io/blob/main/assets/pdf/resume_simplified.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_andrew.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Andrew and I'm a GIS Enterprise Manager. I have experience in Manufacturing Execution Systems and Geographic Information Systems. I have worked at a number of companies managing a variety of projects.

  I am most skilled in: <mark>Windows</mark> and <mark>Linux</mark> system administration.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Resume
        link: https://github.com/andrew3784/andrew3784.github.io/blob/main/assets/pdf/resume_simplified.pdf
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #   Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: British Columbia Institute of Technology
        caption: 2005 - 2007
        sub_title: BTech Geomatics
        quote: >
          Founded in 1964, BCIT has grown from a specialized trades school in Burnaby to a premier polytechnic driving the province's economy.
        description: | # this will include new lines to allow paragraphs
          During my time at BCIT I learnt many of the key skills that have I have taken through my career such as project management and GIS.

          In addition to academic courses, BCIT offers an unparalleled location near Vancouver, offering urban living close to the Pacific Ocean and Coast Mountains.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in information systems my other interests include:
      - Motorcycles
      - Horticulture
      - Cats

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
